Update Jenkinsfile

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -3,6 +3,7 @@ pipeline {
 
     environment {
         DOCKER_IMAGE = "jrishi904/jenkins-demo"
+        IMAGE_TAG = "${env.BUILD_NUMBER}"
     }
 
     stages {
@@ -23,7 +24,9 @@ pipeline {
 
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t $DOCKER_IMAGE -f docker/Dockerfile .'
+                sh '''
+                docker build -t $DOCKER_IMAGE:$IMAGE_TAG -t $DOCKER_IMAGE:latest -f docker/Dockerfile .
+                '''
             }
         }
 
@@ -41,8 +44,36 @@ pipeline {
 
         stage('Push Docker Image') {
             steps {
-                sh 'docker push $DOCKER_IMAGE'
+                sh '''
+                docker push $DOCKER_IMAGE:$IMAGE_TAG
+                docker push $DOCKER_IMAGE:latest
+                '''
             }
+        }
+
+        stage('Deploy Container') {
+            steps {
+                sh '''
+                docker stop jenkins-demo || true
+                docker rm jenkins-demo || true
+                docker run -d -p 3000:3000 --name jenkins-demo $DOCKER_IMAGE:latest
+                '''
+            }
+        }
+
+        stage('Docker Logout') {
+            steps {
+                sh 'docker logout'
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "Pipeline completed successfully 🚀"
+        }
+        failure {
+            echo "Pipeline failed ❌"
         }
     }
 }
